### ISSUE TITLE
Please add a screen shot

### ISSUE THREAD

**Issue by unixorn** [dougalsutherland/djs.zsh-theme#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but I prefer to add themes with screen shots so that users can see what they look like without having to install them.

**Comment by djsutherland** [comment]
Hmm. This is my personal theme that I really haven't tried to make at all general; I don't know if it really makes sense for anyone else to use....

**Comment by unixorn** [comment]
Ok. If you change your mind either @ me or add it to [awesome-zsh-plugin](
https://github.com/unixorn/awesome-zsh-plugin)s in a PR.
